### PR TITLE
#166756346 Redesign the profile page

### PR DESCRIPTION
**Pull request by a-braham**
#### What does this PR do?
  *Change the profile design of the profile page
 
#### Description of Task to be completed?
* Changing the profile outlook
#### How should this be manually tested?
* After cloning the repo:
```
$ git checkout bg-fix-profile-design-166756346
$ npm run start:dev 
```
#### What are the relevant pivotal tracker stories?
[#166756346](https://www.pivotaltracker.com/n/projects/2326460/stories/166756346)
#### Screenshots
Screenshot 2019-06-19 at 12 01 25

### CODE REVIEW

**Comment by Amoswachira** [comment]
@a-braham can you update your screenshots

**Comment by a-braham** [comment]
@Amoswachira  I have updated

**Review by Amoswachira — APPROVED** [review]

**Review by matthenge — APPROVED** [review]
LGTM. Good work on the design

**Review by IssaIan — APPROVED** [review]

**Review by Ogutu-Brian — APPROVED** [review]

**Review by Philipotieno — APPROVED** [review]
Everything looks okay

**Pull request merged**
