### PR TITLE
#166330826 Design a homepage and dummy login

### PR DESCRIPTION
**Pull request by IssaIan**
#### What does this PR do?
Adds a homepage and dummy login page
#### Description of Task to be completed?
Design homepage and a login to test the routing
#### How should this be manually tested?
- Refer to the readme.md
#### What are the relevant pivotal tracker stories?
[#166330826](https://www.pivotaltracker.com/n/projects/2326460/stories/166330826)
#### Screenshots (if appropriate)
**Login Page**
image
**Home page**
image

### CODE REVIEW

**Comment by Philipotieno** [comment]
This looks good

**Review by Amoswachira — APPROVED** [review]
I like the design

**Review by matthenge — CHANGES_REQUESTED** [review]
@IssaIan  Could you change the join now button to be more visible as the sign in button in the home page navbar

**Review by Philipotieno — APPROVED** [review]

**Review by matthenge — APPROVED** [review]
Great design.

**Review by koechkevin — APPROVED** [review]

**Pull request merged**
