### PR TITLE
#165305732-Search and Filter Articles

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
#### What does this PR do?
Adds search functionality to Authors Haven
#### Description of Task to be completed?
1. A user should be able to search for articles through the search tab
2. A user should be able to filter their search by title, author and tags
#### How should this be manually tested?
After cloning the repo:
```
$ git checkout  ft-search-and-filter-165305732
$ npm run start:dev
```
#### Screenshots
image
image

#### What are the relevant pivotal tracker stories?
[#165305732](https://www.pivotaltracker.com/story/show/165305732)

### CODE REVIEW

**Review by Amoswachira — COMMENTED** [review]
you have conflicts

**Review by Amoswachira — APPROVED** [review]

**Review by a-braham — APPROVED** [review]
LGTM

**Review by matthenge — APPROVED** [review]
LGTM

**Review by Philipotieno — APPROVED** [review]
This is a great job you finally managed to test everything that you added  👍

**Review by IssaIan — APPROVED** [review]
LGTM

**Review by Bakley — APPROVED** [review]
Amazing job @Ogutu-Brian

**Pull request merged**
