### PR TITLE
#165305720 Login with Twitter, Facebook, Google

### PR DESCRIPTION
**Pull request by matthenge**
### What does this PR do?
- Allows a user to sign in to Authors Haven with Facebook, Twitter, and Google
### What are the tasks to be completed?
- Develop social auth icons for the Social sites
- Develop social auth functionality using Firebase
- Give appropriate error messages during Social auth
### How can this be manually tested?
After cloning the repo:
```
$ git checkout ft-social-login-165305720
$ npm npm run start:dev
```

### What are the relevant pivotal tracker stories?
[#165305720](https://www.pivotaltracker.com/story/show/165305720)

### Screenshots
image

### CODE REVIEW

**Comment by Ogutu-Brian** [comment]
> ### What does this PR do?
> * Allows a user to sign in to Authors Haven with Facebook, Twitter, and Google
> 
> ### What are the tasks to be completed?
> * Develop social auth icons for the Social sites
> * Develop social auth functionality using Firebase
> * Give appropriate error messages during Social auth
> 
> ### How can this be manually tested?
> After cloning the repo:
> 
> ```
> $ git checkout ft-social-login-165305720
> $ npm npm run start:dev
> ```
> 
> ### What are the relevant pivotal tracker stories?
> [#165305720](https://www.pivotaltracker.com/story/show/165305720)

Hello @matthenge ,
Please add screenshots to the PR. It would help us review the UI look and feel too.

**Review by Ogutu-Brian — COMMENTED** [review]
Hello @matthenge ,
Please add screenshots to the PR description. It would help us review the UI look and feel too.

**Comment by matthenge** [comment]
> Hello @Ogutu-Brian ,
> I will add them as soon as I add the buttons to your feature and @Philipotieno feature.

**Review by Amoswachira — APPROVED** [review]

**Review by IssaIan — APPROVED** [review]
LGTM

**Pull request merged**
